![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on!

In [2]:
import sys
import numpy as np

## Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [19]:
np.array([1, 2, 3, 4], dtype=np.float16)

array([1., 2., 3., 4.], dtype=float16)

In [20]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [21]:
c = np.array(['a', 'b', 'c'])

In [22]:
c.dtype

dtype('<U1')

In [23]:
d = np.array([{'a': 1}, sys])

In [24]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [26]:
A.shape

(2, 3)

In [27]:
A.ndim

2

In [28]:
A.size

6

In [29]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [30]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [31]:
B.shape

(2, 2, 3)

In [32]:
B.ndim

3

In [33]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [34]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [35]:
C.dtype

NameError: name 'C' is not defined

In [36]:
C.shape

NameError: name 'C' is not defined

In [37]:
C.size

NameError: name 'C' is not defined

In [38]:
type(C[0])

NameError: name 'C' is not defined

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [39]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [40]:
A[1]

array([4, 5, 6])

In [41]:
A[1][0]

4

In [42]:
# A[d1, d2, d3, d4]

In [43]:
A[1, 0]

4

In [44]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [46]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [47]:
A[:2, 2:]

array([[3],
       [6]])

In [48]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
A[1] = np.array([10, 10, 10])

In [50]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [51]:
A[2] = 99

In [52]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [53]:
a = np.array([1, 2, 3, 4])

In [54]:
a.sum()

10

In [55]:
a.mean()

2.5

In [56]:
a.std()

1.118033988749895

In [57]:
a.var()

1.25

In [58]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [59]:
A.sum()

45

In [60]:
A.mean()

5.0

In [61]:
A.std()

2.581988897471611

In [62]:
A.sum(axis=0)

array([12, 15, 18])

In [63]:
A.sum(axis=1)

array([ 6, 15, 24])

In [64]:
A.mean(axis=0)

array([4., 5., 6.])

In [65]:
A.mean(axis=1)

array([2., 5., 8.])

In [66]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [67]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [68]:
a = np.arange(4)

In [69]:
a

array([0, 1, 2, 3])

In [70]:
a + 10

array([10, 11, 12, 13])

In [71]:
a * 10

array([ 0, 10, 20, 30])

In [72]:
a

array([0, 1, 2, 3])

In [73]:
a += 100

In [74]:
a

array([100, 101, 102, 103])

In [75]:
l = [0, 1, 2, 3]

In [76]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [77]:
a = np.arange(4)

In [78]:
a

array([0, 1, 2, 3])

In [79]:
b = np.array([10, 10, 10, 10])

In [80]:
b

array([10, 10, 10, 10])

In [81]:
a + b

array([10, 11, 12, 13])

In [82]:
a * b

array([ 0, 10, 20, 30])

**There is an error in the question of this particular video**

In [3]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [83]:
a = np.arange(4)

In [84]:
a

array([0, 1, 2, 3])

In [85]:
a[0], a[-1]

(0, 3)

In [86]:
a[[0, -1]]

array([0, 3])

In [87]:
a[[True, False, False, True]]

array([0, 3])

In [88]:
a

array([0, 1, 2, 3])

In [89]:
a >= 2

array([False, False,  True,  True])

In [90]:
a[a >= 2]

array([2, 3])

In [91]:
a.mean()

1.5

In [92]:
a[a > a.mean()]

array([2, 3])

In [93]:
a[~(a > a.mean())]

array([0, 1])

In [94]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [95]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [96]:
A = np.random.randint(100, size=(3, 3))

In [97]:
A

array([[89, 52, 76],
       [63, 81,  2],
       [94, 82,  9]])

In [98]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([89, 76, 81, 94,  9])

In [99]:
A > 30

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True, False]])

In [100]:
A[A > 30]

array([89, 52, 76, 63, 81, 94, 82])

**The Question for this specific part of the Boolea Alegra**

In [4]:
a = np.arange(5)
print (a <= 3)

[ True  True  True  True False]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [5]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [6]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [7]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [8]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [9]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [10]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [12]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [13]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [14]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [15]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [16]:
np.dtype(float).itemsize

8

### Lists are even larger

In [18]:
# A one-element list
sys.getsizeof([1])

64

In [19]:
# An array of one element in numpy
np.array([1]).nbytes

4

### And performance is also important

In [20]:
l = list(range(100000))

In [21]:
a = np.arange(100000)

In [22]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 1 ms


216474736

In [23]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 39.8 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random`

In [24]:
np.random.random(size=2)

array([0.84909164, 0.47716565])

In [25]:
np.random.normal(size=2)

array([ 1.061995  , -1.23155433])

In [26]:
np.random.rand(2, 4)

array([[0.36212668, 0.96176569, 0.16665836, 0.31997573],
       [0.25083859, 0.28732625, 0.27789914, 0.98830672]])

---
### `arange`

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [29]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [30]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [32]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [34]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.zeros((3, 3), dtype=np.int16)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [41]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [42]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [47]:
"Hello World"[6]

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)